name: Pytest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install

      - name: Install dependencies
        run: uv sync --dev

      - name: Check if there are any test files
        run: |
          if [ -z "$(find tests -name 'test_*.py' 2>/dev/null)" ]; then
            echo "No test files found"
            echo "NO_TEST_FILES=true" >> "$GITHUB_ENV"
          fi

      - name: Skip further steps if no test files
        if: env.NO_TEST_FILES == 'true'
        run: echo "No test files found, skipping tests."

      - name: Run tests with pytest
        if: env.NO_TEST_FILES != 'true'
        run: uv run pytest